apiVersion: v1
kind: Secret
metadata:
  name: aws-creds
  namespace: garden
  labels:
    cloudprofile.garden.sapcloud.io/name: aws_cloudprofile  # label is only meaningful for Gardener dashboard
type: Opaque
data:
  accessKeyID: XXXXXXXXXXXXXXXXXXXXXXXX
  secretAccessKey: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
